# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d8c07002a083fb27a953d8ce2184d05ad39cec74e16499228589df504f5fbc6023f072918d3b0205a169f00923d5bf3a9e583022d6bbcdbc558250c687baaa2

test:
  secret_key_base: e1fd55a142711a4f37db2681bbff8c35056547406a8ce40a9d996c7355c3b9bb4a3d9a149dfab62ca3737615e0f1831952ad2dd65e245cabbf1beb9c201fad39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
